export = {
    "echo": {
        "title": "echo",
        "description": "sends back the message received.",
        "category": "standard",
        "fileReference": "echo.js",
        "hasArgs": true,
        "isAlias": false,
    },
    "manual": {
        "title": "manual",
        "description": "",
        "category": "standard",
        "fileReference": "manual.js",
        "hasArgs": true,
        "isAlias": false,
    },
    "logmein": {
        "title": "logmein",
        "description": "",
        "category": "standard",
        "fileReference": "logmein.js",
        "hasArgs": false,
        "isAlias": false,
    },
    "daily": {
        "title": "daily",
        "description": "",
        "category": "currency",
        "fileReference": "daily.js",
        "hasArgs": true,
        "isAlias": false,
    },
    "transfer": {
        "title": "transfer",
        "description": "",
        "category": "currency",
        "fileReference": "transfer.js",
        "hasArgs": true,
        "isAlias": false,
    },
    "credits": {
        "title": "credits",
        "description": "",
        "category": "currency",
        "fileReference": "credits.js",
        "hasArgs": true,
        "isAlias": false,
    },
}
